<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>SkkmConnector</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageId>SkkmConnector</PackageId>
    <Version>1.26.1</Version>
    <Authors>rbsoft</Authors>
    <Company>rbsoft</Company>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

</Project>
